site_name: Cmd Hub Docs
site_description: Documentation site
site_author: Cmd Hub
theme:
  name: material
extra_css:
  - assets/css/cmdhub.css
nav:
  - Home: index.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
plugins:
  - search
